package Entities;

// Generated May 4, 2017 5:46:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "test")
public class Person implements java.io.Serializable {

  private Integer avatarId;
  private byte[] image;

  public Person() {
  }

  public Person(byte[] image) {
    this.image = image;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "avatarId", unique = true, nullable = false)
  public Integer getAvatarId() {
    return this.avatarId;
  }

  public void setAvatarId(Integer avatarId) {
    this.avatarId = avatarId;
  }

  @Column(name = "image")
  public byte[] getImage() {
    return this.image;
  }

  public void setImage(byte[] image) {
    this.image = image;
  }

}
